# Generated by Django 3.2.13 on 2022-11-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_awardmovie_award_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award_movie',
            old_name='title',
            new_name='titel',
        ),
    ]
