# Generated by Django 3.2.13 on 2022-11-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_title_award_movie_titel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award_movie',
            old_name='vote_acerage',
            new_name='vote_average',
        ),
    ]
