# Generated by Django 3.2.13 on 2022-11-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_vote_acerage_award_movie_vote_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award_movie',
            name='release_date',
            field=models.CharField(max_length=4),
        ),
    ]
